apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  labels:
    app: demo-app
spec:
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
       - name: my-container
         image: nginx
         ports:
          - containerPort: 80
  replicas: 3
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [cbz-app]}
  strategy:
    type: RollingUpdate
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: demo-app
  name: my-deploy-svc
spec:
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      name: http
  selector:
    app: demo-app
  type: NodePort