apiVersion: v1 
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0972673acc3a0b590
    fsType: ext4
    volumeAttributes: 
      storage.kuberentes.io/csiProvisionerIdentity: static
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - {key: topology.kubernetes.io/zone, operator: In, values: ["us-east-1a"]}