apiVersion: v1 
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: my-app
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessMode: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/data