apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
       - name: nginx-app
         image: nginx
         ports:
          - containerPort: 80
  replicas: 3
  selector:
    app: my-app

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: my-app
  name: my-svc
spec:
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      name: http
  selector:
    app: my-app
  type: NodePort
