apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress    
spec:
  rules:
  - http:
      paths:
        - path: /cloth
          pathType: Prefix
          backend:
            service:
              name: cloth-app-svc
              port:
                number: 80
        - path: /mobile
          pathType: Prefix
          backend:
            service:
              name: mobile-app-svc
              port:
                number: 80    


# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.13.3/deploy/static/provider/cloud/deploy.yaml